### ISSUE TITLE
[Bug] Failed to load avatar in wrap analysis 

### ISSUE THREAD

**Issue by zrll12** [pizza-studio/HSRPizzaHelper#179]
**Describe the bug**
Failed to load avatar of the wrap analysis 

**To Reproduce**
1. Go to 'tools'
2. Click on 'Wrap analysis'
3. Open one of them

**Screenshots**
![image](https://github.com/pizza-studio/HSRPizzaHelper/assets/46812903/85a60c4a-b716-4160-81b7-e5ed844e1167)

**System (please complete the following information):**
 - Device: iPhone 14 Pro Max 
 - OS: iOS 17.1
 - Version 1.3.1
 - Build 335

**Comment by ShikiSuen** [comment]
This issue has been solved in v1.3.2.
