### ISSUE TITLE
[Bug]Incorrect genshin display

### ISSUE THREAD

**Issue by czz4188** [pizza-studio/HSRPizzaHelper#202]
![2A1AF306-0437-434B-A184-83C490EFE7A3](https://github.com/pizza-studio/HSRPizzaHelper/assets/172411435/da5b9390-0e83-40e8-b5cb-b2947e7037ad)
Like what shown in the image,it should be “星穹列车”and others

**Comment by ShikiSuen** [comment]
@czz4188 目前是故意这么写的，因为原神玩家群体远远比星穹铁道玩家群体要多。
下一版更新开始会用括号加注成「天空岛（星穹列车）＆世界树（无名客）」。

**Comment by ShikiSuen** [comment]
备忘：或可将这两个伺服器改称「miHoYoHQ」与「bilibili」。

**Comment by ShikiSuen** [comment]
<img width="534" alt="image" src="https://github.com/user-attachments/assets/52261881-95c5-43f5-a5df-bc1047cc1f13">

搞定，会推送到 v1.4.0 版 App 更新内。
