### ISSUE TITLE
[Bug]Error when exporting warp records

### ISSUE THREAD

**Issue by Lucas04-nhr** [pizza-studio/HSRPizzaHelper#211]
**Describe the bug**
导出SRGF格式的抽卡记录无反应
The app has no response when trying to export Warp Record in SRGF format.

**To Reproduce**
https://github.com/user-attachments/assets/00ba4bc1-283d-4faf-9e54-677f2ae3d11e

**Screenshots**
See screen recording above.
参见上方屏幕录制

**System (please complete the following information):**
 - Device:iPad Air 5
 - OS: iPadOS 17.6
 - Version 1.4.2
 - Build 854

**Comment by ShikiSuen** [comment]
故障的实质：iOS 17 这一代的 SwiftUI 无法正确处理「某个 View 被连续挂了两个 fileExporter」的情况。

我检查一下 iOS 18 是否也会有这个情况，不行的话就换个 View 构建思路。

<img width="389" alt="image" src="https://github.com/user-attachments/assets/5d167af8-907b-43b8-b4cf-3b6bba4fd19e">

**Comment by ShikiSuen** [comment]
Fixed by creating a shared SwiftUI Document struct for both UIGFv4 and SRGFv1.
This reduces the needs of duplicating fileExporter hooks.

**Comment by ShikiSuen** [comment]
@Lucas04-nhr 该修正将随 1.4.3 版更新推送。该更新预计会在星穹铁道 2.5 开服前后送审。
